# Generated by Django 4.2.1 on 2023-06-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='наименование услуги')),
                ('description', models.TextField(verbose_name='описание услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now=True, verbose_name='время заказа')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.service')),
            ],
        ),
    ]
