# Generated by Django 4.2.1 on 2023-06-05 17:20

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_service_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2023)], verbose_name='год выпуска'),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='polls.service'),
        ),
    ]
