# Generated by Django 4.2.5 on 2023-09-13 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_order_name_order_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='ответ')),
                ('answer', models.TextField(verbose_name='вопрос')),
                ('date', models.DateField(auto_now=True, verbose_name='дата добавления')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+375441111111', max_length=13, validators=[django.core.validators.RegexValidator('^\\+375?\\d{9}$', "Phone number must be entered in the format: '+999999999'")], verbose_name='номер телефона'),
        ),
    ]
