# Generated by Django 4.2.5 on 2023-09-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_driver_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='Employees',
        ),
    ]
