# Generated by Django 4.2.5 on 2023-09-14 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_employees_email_employees_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(default='', upload_to='photos/%Y/%m/%d')),
                ('date', models.DateField(auto_now=True, verbose_name='дата добавления')),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator('')], verbose_name='эл. почта'),
        ),
    ]
