# Generated by Django 4.2.5 on 2023-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_news_alter_employees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=models.TextField(default='', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
